trigger:
  branches:
    include:
    - main
pool:
  vmImage: ubuntu-latest
  
variables:
- name: location
  value: 'eastus'
- name: resourceGroup
  value: 'rg-ntier'
- name: vNetName
  value: 'vnet-ntier'
stages:
- stage: Deploy_Network
  jobs:
  - job: Create_RG_VNet_Subnets
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/01-deploy-Criar-grupo-de-recursos'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/02-deploy-Criar-vnet-e-a-subnet-do-Application-Gateway'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/03-deploy-Criar-subnet-de-gerenciamento'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/04-deploy-Criar-subnet-Web'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/05-deploy-Criar-subnet-Business'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/06-deploy-Criar-subnet-Data'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/07-deploy-Criar-subnet-Entra-ID'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
- stage: Configure_NSGs
  dependsOn:
  - Deploy_Network
  jobs:
  - job: Create_NSGs_And_Associate
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/08-deploy-Criar-NSGs'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/09-deploy-Criando-regras-para-os-NSG'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: "Script/10-deploy-Associar-os-NSGs-as-subnets"
        workingDirectory: '$(System.DefaultWorkingDirectory)'
- stage: Deploy_Bastion
  dependsOn:
  - Configure_NSGs
  jobs:
  - job: Run_Deploy_Bastion
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/11-deploy-Criar-bastion-host'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
- stage: Deploy_Web_Layer
  dependsOn:
  - Deploy_Bastion
  jobs:
  - job: Run_Deploy_Web_Layer
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/12-deploy-Criar-máquinas-virtuais-da-camada-web'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: "Script/13-deploy-Criar-IPs-das-máquinas-da-camada-web-para-APPGW"
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/14-deploy-Criar-Application-Gateway'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
- stage: Configure_DNS
  dependsOn:
  - Deploy_Web_Layer
  jobs:
  - job: Run_Configure_DNS
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/15-deploy-Criar-uma-zona-DNS'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/16-deploy-Criar-um-registro-DNS'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
- stage: Enable_DDoS
  dependsOn:
  - Configure_DNS
  jobs:
  - job: Run_Enable_DDoS
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/17-deploy-Criar-DDoS'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
- stage: Deploy_Business_Layer
  dependsOn:
  - Enable_DDoS
  jobs:
  - job: Run_Deploy_Business_Layer
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/18-deploy-Criar-o-recurso-do-balanceador-de-carga'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/19-deploy-Criar-uma-investigação-de-integridade'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/20-deploy-Criar-uma-regra-de-balanceador-de-carga'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/21-deploy-Criar-máquinas-virtuais-da-camada-Business'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/22-deploy-Adicionar-VMs-ao-pool-de-back-end'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/23-deploy-Criar-uma-regra-de-saída-no-NSG-LB-Business'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
- stage: Deploy_Data_Layer
  dependsOn:
  - Deploy_Business_Layer
  jobs:
  - job: Run_Deploy_Data_Layer
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/24-deploy-Criar-o-recurso-de-LB-da-camada-de-Banco-de-Dados'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/25-deploy-Criar-a-investigação-de-integridade'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/26-deploy-Criar-uma-regra-de-LB'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/27-deploy-Criar-VM-da-camada-Business'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/28-deploy-Adicionar-máquinas-virtuais-ao-pool-de-back-end'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/29-deploy-Criar-uma-regra-de-saída-no-NSG-da-camada-web'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/30-deploy-Criar-Azure-LB-da-camada-de-Banco-de-dados'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/31-deploy-Criar-a-investigacao-de-integridade'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/32-deploy-Criar-uma-regra-de-balanceador-de-carga'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/33-deploy-Criar-uma-conta-de-armazenamento'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/34-deploy-Criar-VMs-da-camada-de-Banco-de-Dados'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/35-deploy-Adicionar-VMs-ao-pool-de-back-end'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/36-deploy-Criar-uma-regra-de-saída-no-NSG-da-camada-Bussiness'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
- stage: Deploy_ADDS
  dependsOn:
  - Deploy_Data_Layer
  jobs:
  - job: Run_Deploy_ADDS
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        scriptType: 'bash'
        ScriptPath: 'Script/37-deploy-Criar-máquinas-virtuais-da-camada-ADDS'
        workingDirectory: '$(System.DefaultWorkingDirectory)'