trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $scriptPath = "$(Build.SourcesDirectory)/main/scripts"
      Write-Host "Verificando scripts em: $scriptPath"
      dir $scriptPath

      Get-ChildItem "$scriptPath" -Filter *.ps1 | ForEach-Object {
          Write-Host "Executando $($_.Name)..."
          & $_.FullName
      }
    displayName: 'Executar todos os scripts PowerShell da pasta'
