trigger:
  branches:
    include:
      - main
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzureServiceConnection'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      Get-ChildItem "$(Build.SourcesDirectory)/main/scripts" -Filter *.ps1 |
      ForEach-Object {
        Write-Output "Executando $($_.Name)..."
        & $_.FullName
      }
