trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  location: 'eastus'
  resourceGroup: 'rg-ntier'
  vNetName: 'vnet-ntier'

stages:
- stage: Deploy_Network
  jobs:
  - job: Create_RG_VNet_Subnets
    steps:
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'Seu-Servico-Conexao'
        ScriptType: 'FilePath'
        ScriptPath: 'Script/01-deploy-Criar grupo de recursos.ps1'
        azurePowerShellVersion: 'LatestVersion'
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'Seu-Servico-Conexao'
        ScriptType: 'FilePath'
        ScriptPath: 'Script/02-deploy-Criar vnet e a subnet do Application Gateway.ps1'
        azurePowerShellVersion: 'LatestVersion'
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'Seu-Servico-Conexao'
        ScriptType: 'FilePath'
        ScriptPath: 'Script/03-deploy-Criar subnet de gerenciamento.ps1'
        azurePowerShellVersion: 'LatestVersion'
    # Continue com os scripts 04, 05, 06, 07...

- stage: Configure_NSGs
  dependsOn: Deploy_Network
  jobs:
  - job: Create_NSGs_And_Associate
    steps:
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'Seu-Servico-Conexao'
        ScriptType: 'FilePath'
        ScriptPath: 'Script/08-deploy-Criar NSGs.ps1'
        azurePowerShellVersion: 'LatestVersion'
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'Seu-Servico-Conexao'
        ScriptType: 'FilePath'
        ScriptPath: 'Script/09-deploy-Criando regras para os NSG.ps1'
        azurePowerShellVersion: 'LatestVersion'
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'Seu-Servico-Conexao'
        ScriptType: 'FilePath'
        ScriptPath: "Script/10-deploy-Associar os NSG's às subnets.ps1"
        azurePowerShellVersion: 'LatestVersion'

