trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Get-ChildItem "$(Build.SourcesDirectory)/main/Script" -Filter *.ps1 |
      ForEach-Object {
          Write-Host "Executando $($_.Name)..."
          & $_.FullName
      }
