trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  location: 'eastus'
  resourceGroup: 'rg-ntier'
  vNetName: 'vnet-ntier'

stages:
- stage: Deploy_Network
  jobs:
  - job: Create_RG_VNet_Subnets
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/01-deploy-Criar grupo de recursos.ps1'
     
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/02-deploy-Criar vnet e a subnet do Application Gateway.ps1'
     
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/03-deploy-Criar subnet de gerenciamento.ps1'
 

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/01-deploy-Criar grupo de recursos.ps1'
     
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/02-deploy-Criar vnet e a subnet do Application Gateway.ps1'
  
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/03-deploy-Criar subnet de gerenciamento.ps1'
  
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/04-deploy-Criar subnet Web.ps1'
     
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/05-deploy-Criar subnet Business.ps1'
    
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/06-deploy-Criar subnet Data.ps1'
     
  
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/07-deploy-Criar subnet Entra ID.ps1'
   

- stage: Configure_NSGs
  dependsOn: Deploy_Network
  jobs:
  - job: Create_NSGs_And_Associate
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/08-deploy-Criar NSGs.ps1'
  
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/09-deploy-Criando regras para os NSG.ps1'
    
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: "Script/10-deploy-Associar os NSG's às subnets.ps1"
     

- stage: Deploy_Bastion
  dependsOn: Configure_NSGs
  jobs:
  - job: Run_Deploy_Bastion
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/11-deploy-Criar bastion host.ps1'
     

- stage: Deploy_Web_Layer
  dependsOn: Deploy_Bastion
  jobs:
  - job: Run_Deploy_Web_Layer
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/12-deploy-Criar máquinas virtuais da camada web.ps1'
      
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: "Script/13-deploy-Criar ip's das máquinas da camada web para APPGW.ps1"
       
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/14-deploy-Criar Application Gateway.ps1'


- stage: Configure_DNS
  dependsOn: Deploy_Web_Layer
  jobs:
  - job: Run_Configure_DNS
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/15-deploy-Criar uma zona DNS.ps1'
     
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/16-deploy-Criar um registro DNS.ps1'
    

- stage: Enable_DDoS
  dependsOn: Configure_DNS
  jobs:
  - job: Run_Enable_DDoS
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/17-deploy-Criar DDoS.ps1'
  

- stage: Deploy_Business_Layer
  dependsOn: Enable_DDoS
  jobs:
  - job: Run_Deploy_Business_Layer
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/18-deploy-Criar o recurso do balanceador de carga.ps1'
       
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/19-deploy-Criar uma investigação de integridade.ps1'
  
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/20-deploy-Criar uma regra de balanceador de carga.ps1'
     

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/21-deploy-Criar máquinas virtuais da camada Business.ps1'
       
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/22-deploy-Adicionar VMs ao pool de back-end.ps1'
        
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/23-deploy-Criar uma regra de saída no NSG LB Business.ps1'
        
- stage: Deploy_Data_Layer
  dependsOn: Deploy_Business_Layer
  jobs:
  - job: Run_Deploy_Data_Layer
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/24-deploy-Criar o recurso de LB da camada de Banco de Dados.ps1'
        
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/25-deploy-Criar a investigação de integridade.ps1'
       
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/26-deploy-Criar uma regra de LB.ps1'
        
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/30-deploy-Criar Azure LB da camada de Banco de dados.ps1'
      
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/31-deploy-Criar a investigação de integridade.ps1'
       
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/32-deploy-Criar uma regra de balanceador de carga.ps1'
   

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/34-deploy-Criar VMs da camada de Banco de Dados.ps1'
        

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/35-deploy-Adicionar VMs ao pool de back-end.ps1'
      
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/36-deploy-Criar uma regra de saída no NSG da camada Bussiness.ps1'
      
- stage: Deploy_ADDS
  dependsOn: Deploy_Data_Layer
  jobs:
  - job: Run_Deploy_ADDS
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptLocation: 'scriptPath'
        ScriptPath: 'Script/37-deploy-Criar máquinas virtuais da camada ADDS.ps1'
       
