trigger:
- main   # dispara quando há commit na branch main

pool:
  vmImage: 'ubuntu-latest'   # agente hospedado pelo Azure

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'   # versão do Node.js
  displayName: 'Instalar Node.js'

- script: npm install
  displayName: 'Instalar dependências'

- script: npm run build
  displayName: 'Build do projeto'

- script: npm test
  displayName: 'Executar testes'

