trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: '$(Build.SourcesDirectory)/main/Script/01-deploy-Criar grupo de recursos.ps1'

- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: '$(Build.SourcesDirectory)/main/Script/02-deploy-Criar vnet e a subnet do Application Gateway.ps1'
