#!/bin/bash
$resourceGroup = "rg-ntier"
$vNetName = "vnet-ntier"
$subnetBusinessName = "subnet-business"
$lbName = "lbBusiness"
$frontendIpName = "frontEndBusiness"
$backendPoolName = "backEndPoolBusiness"

az network lb create `
--resource-group $resourceGroup `
--name $lbName `
--sku Standard `
--vnet-name $vNetName `
--subnet $subnetBusinessName `
--frontend-ip-name $frontendIpName `
--backend-pool-name $backendPoolName
 
